-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


-- 產品類別型別
CREATE TYPE product_class AS ENUM ('主打套餐', '漢堡', '炸雞', '捲餅', '沙拉', '小吃', '飲料', '甜點')


-- 產品表
CREATE TABLE IF NOT EXISTS public."Products"
(
    product_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    product_name text NOT NULL,
    "image_URL" text NOT NULL,
    making_time time without time zone NOT NULL,
    product_price money NOT NULL,
    product_class product_class NOT NULL, -- 產品類別
    product_illustrate text NOT NULL, -- 產品說明
    PRIMARY KEY (product_id)
);

-- 規格表
CREATE TABLE IF NOT EXISTS public."Products_Specification"
(
    specification_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    product_id integer NOT NULL,
    specification_name text NOT NULL,
    PRIMARY KEY (specification_id),
    FOREIGN KEY (product_id) REFERENCES public."Products" (product_id)
);



-- 會員表
CREATE TABLE IF NOT EXISTS public."Member"
(
    member_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    member_name text NOT NULL,
    member_phone character varying(20) NOT NULL,
    member_gender boolean,
    member_birthday date,
    member_password character varying(128) NOT NULL,
    PRIMARY KEY (member_id)
);

-- 點數卡表
CREATE TABLE IF NOT EXISTS public."Points_Card"
(
    point_card_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    member_id integer NOT NULL,
    PRIMARY KEY (point_card_id),
    FOREIGN KEY (member_id) REFERENCES public."Member" (member_id)
);

-- 點數表
CREATE TABLE IF NOT EXISTS public."Point_Details"
(
    point_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    point_expired_date date NOT NULL,
    point_card_id integer NOT NULL,
    PRIMARY KEY (point_id),
    FOREIGN KEY (point_card_id) REFERENCES public."Points_Card" (point_card_id)
);

-- 付款表
CREATE TABLE IF NOT EXISTS public."Payment"
(
    payment_id integer NOT NULL,
    payment_date date NOT NULL,
    payment_method text NOT NULL, -- 付款方式
    payment_status boolean NOT NULL, -- 付款狀態
    PRIMARY KEY (payment_id)
);

-- 訂單類別型別
CREATE TYPE order_type AS ENUM
(
    'Dine_In', -- 內用
    'Takeout' -- 外帶
);

-- 訂單表
CREATE TABLE IF NOT EXISTS public."Orders"
(
    order_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    member_id integer,
    payment_id integer, --訂單付款後才會有付款id
    order_date date NOT NULL,
    order_type order_type NOT NULL,
    PRIMARY KEY (order_id),
    FOREIGN KEY (member_id) REFERENCES public."Member" (member_id),
    FOREIGN KEY (payment_id) REFERENCES public."Payment" (payment_id)
);
    
    -- 訂單->內用表
    CREATE TABLE IF NOT EXISTS public."Dine_In"
    (
        dine_in_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
        order_id integer NOT NULL,
        table_id integer NOT NULL,
        PRIMARY KEY (dine_in_id),
        FOREIGN KEY (order_id) REFERENCES public."Orders" (order_id)
    );


    -- 訂單->外帶表
    CREATE TABLE IF NOT EXISTS public."Takeout"
    (
        takeout_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
        order_id integer NOT NULL,
        takeout_type text check (takeout_type in ('Online', 'On_The_Spot')) NOT NULL ,
        meal_note text NOT NULL,
        meal_type text NOT NULL, -- todo: meal_type 設定
        PRIMARY KEY (takeout_id),
        FOREIGN KEY (order_id) REFERENCES public."Orders" (order_id)
    );

        -- 訂單->外帶->線上點餐
        CREATE TABLE IF NOT EXISTS public."Online"
        (
            online_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
            takeout_id integer NOT NULL,
            PRIMARY KEY (online_id),
            FOREIGN KEY (takeout_id) REFERENCES public."Takeout" (takeout_id)
        );
       


        -- 訂單->外帶->現場點餐
        CREATE TABLE IF NOT EXISTS public."On_The_Spot"
        (
            spot_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
			takeout_id integer NOT NULL,
            PRIMARY KEY (spot_id),
            FOREIGN KEY (takeout_id) REFERENCES public."Takeout" (takeout_id)
        );

-- 訂單明細表
CREATE TABLE IF NOT EXISTS public."Order_Details"
(
    order_detail_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    specification_id integer NOT NULL,
    PRIMARY KEY (order_detail_id),
    FOREIGN KEY (order_id) REFERENCES public."Orders" (order_id),
    FOREIGN KEY (product_id) REFERENCES public."Products" (product_id),
    FOREIGN KEY (specification_id) REFERENCES public."Products_Specification" (specification_id)
);


END;